### ISSUE TITLE
Create logic to allow users to edit his profile:

### ISSUE THREAD

**Issue by rubenpad** [dejavuhq/sub-routines-backend#5]
Create Profile model with relation one to one with user model that supports next fields:

- Profile picture
- Biography

Also create logic and endpoint to allow users edit his profile.

**Comment by macknilan** [comment]
Commit c2236bb
[ADD] Added _User Profile_ to integrate the _Biography_ field and the _Profile Image_ and makes the user profile CRUD through the API endpoints
